version: "2"

services:
  smtp:
    image: namshi/smtp:latest
    mem_limit: 32m
    expose:
      - "25"
    ports:
      - "10025:25"
    networks:
      backend:
        aliases:
          - smtp.comet-watcher.com
  db:
    image: mongo:4.2.7
    mem_limit: 64m
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      backend:
        aliases:
          - database.comet-watcher.com
  app:
    image: eshishkin/comet-watcher:latest
    mem_limit: 128m
    expose:
      - "8080"
    ports:
      - "18080:8080"
    depends_on:
      - smtp
      - db
    networks:
      backend:

networks:
  backend:
