version: "2"

services:
  smtp:
    image: namshi/smtp:latest
    mem_limit: 32m
    expose:
      - "25"
    networks:
      backend:
        aliases:
          - smtp.comet-watcher.com
  db:
    image: apache/couchdb:latest
    mem_limit: 64m
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    expose:
      - "5984"
    volumes:
      - comet-watcher-db:/var/lib/couchdb
    networks:
      backend:
        aliases:
          - database.comet-watcher.com
  app:
    image: eshishkin/comet-watcher:latest
    mem_limit: 128m
    expose:
      - "8080"
    ports:
      - "18080:8080"
    depends_on:
      - smtp
      - db
    networks:
      backend:

networks:
  backend:

volumes:
  comet-watcher-db: