version: "2"

services:
  smtp:
    image: namshi/smtp:latest
    mem_limit: 32m
    expose:
      - "25"
    ports:
      - "10025:25"
    networks:
      backend:
        aliases:
          - smtp.comet-watcher.com
  db:
    image: apache/couchdb:latest
    mem_limit: 64m
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    expose:
      - "5984"
    ports:
      - "5984:5984"
    networks:
      backend:
        aliases:
          - database.comet-watcher.com

networks:
  backend:
