apiVersion: v2
type: application

name: comet-watcher
version: 1.3.0

description: A simple web service that periodically sends data about upcoming comets to email

dependencies:
  - name: vault
    version: 0.7.0
    repository: https://helm.releases.hashicorp.com
#    import-values: # (optional)
#      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.