quarkus:
  banner:
    path: banner.txt
  log:
    level: INFO
  mailer:
    from: comet-watcher@example.com
    mock: true

application:
  external:
    url:
      heavens-above: https://www.heavens-above.com
  schedulers:
    comet-notifier: 0 0/4 * * * ?
  mail:
    templates:
      comet-report:
        subject: Test message from Quarkus App


###############################################
###### Properties for testing in docker #######
###############################################
"%docker":
  quarkus:
    mailer:
      host: localhost
      port: 10025
      mock: false
  repository:
    subscribers:
      url: http://localhost:5984
      user: admin
      password: password