apiVersion: v1
kind: Service
metadata:
  name: comet-watcher-smtp
spec:
  ports:
    - port: 25
      targetPort: 25
  selector:
    app: comet-watcher-smtp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comet-watcher-smtp
  labels:
    app: comet-watcher-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comet-watcher-smtp
  template:
    metadata:
      labels:
        app: comet-watcher-smtp
    spec:
      volumes:
      containers:
        - name: smtp
          image: namshi/smtp:latest