# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with GraalVM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up GraalVM
      uses: rinx/setup-graalvm-ce@v0.0.4
      with:
        graalvm-version: "19.3.1"
        java-version: "java11"
        native-image: "true"
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-graal-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B -Pnative clean package --file pom.xml
    - uses: satackey/action-docker-layer-caching@v0.0.3
      with:
        key: ${{ runner.os }}-docker-cache-{hash}
        restore-keys: |
          ${{ runner.os }}-docker-cache-
    - name: Integration tests
      run: mvn -B test-compile failsafe:integration-test
